
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLASS DIVIDE DOT IDENTIFIER LBRACE LBRACKET LPAREN MAIN MINUS NUMBER PLUS PUBLIC RBRACE RBRACKET RPAREN SEMICOLON STATIC STRING STRING_LITERAL SYSOUT TIMES VOID\n    program : PUBLIC CLASS IDENTIFIER LBRACE main_method RBRACE\n    \n    main_method : PUBLIC STATIC VOID MAIN LPAREN STRING LBRACKET RBRACKET IDENTIFIER RPAREN close\n    \n    close : LBRACE system_out RBRACE\n    \n    system_out : SYSOUT LPAREN RPAREN SEMICOLON\n    '
    
_lr_action_items = {'PUBLIC':([0,5,],[2,6,]),'$end':([1,9,],[0,-1,]),'CLASS':([2,],[3,]),'IDENTIFIER':([3,15,],[4,16,]),'LBRACE':([4,17,],[5,19,]),'STATIC':([6,],[8,]),'RBRACE':([7,18,20,22,25,],[9,-2,22,-3,-4,]),'VOID':([8,],[10,]),'MAIN':([10,],[11,]),'LPAREN':([11,21,],[12,23,]),'STRING':([12,],[13,]),'LBRACKET':([13,],[14,]),'RBRACKET':([14,],[15,]),'RPAREN':([16,23,],[17,24,]),'SYSOUT':([19,],[21,]),'SEMICOLON':([24,],[25,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'main_method':([5,],[7,]),'close':([17,],[18,]),'system_out':([19,],[20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PUBLIC CLASS IDENTIFIER LBRACE main_method RBRACE','program',6,'p_program','app.py',86),
  ('main_method -> PUBLIC STATIC VOID MAIN LPAREN STRING LBRACKET RBRACKET IDENTIFIER RPAREN close','main_method',11,'p_main_method','app.py',92),
  ('close -> LBRACE system_out RBRACE','close',3,'p_close','app.py',98),
  ('system_out -> SYSOUT LPAREN RPAREN SEMICOLON','system_out',4,'p_system_out','app.py',104),
]
